[config]
skip_core_tasks = true

[tasks.clean]
script = [
    "rm -rf build",
    "mkdir build",
]

[tasks.build-js]
script = [
    "npx -p typescript tsc --strict --noUncheckedIndexedAccess --noEmitOnError --lib esnext,dom,esnext --target esnext --module es6 --outDir build-js src/ts/main.ts src/ts/wasm_init.ts",
    "npx rollup build-js/main.js --file build/index.js",
    "rm -rf build-js",
]

[tasks.build-wasm]
script = [
    "cargo build --release --target wasm32-unknown-unknown",
    "cp target/wasm32-unknown-unknown/release/wasm_klej.wasm build/binary.wasm",
    "cp src/index.html build",
]

[tasks.build]
dependencies = [
    "clean",
    "build-js",
    "build-wasm",
]

[tasks.serve]
dependencies = [ "build" ]
install_crate = { crate_name = "basic-http-server", binary = "basic-http-server", test_arg = ["--version"] }
command = "basic-http-server"
args = [ "--addr", "127.0.0.1:4444", "./build" ]

[tasks.watch]
command = "cargo"
args = [ "watch", "--watch", "./src", "--delay", "0.5", "-x", "make serve" ]
